### PR TITLE
Fix version check

### PR DESCRIPTION
**Pull request by User-green**
- [x] Fix version chek
```
- [ ] Rewrite input system to be compadable with arrow keys
- [ ] Add mobile (termux) support
```
Removed due to how `discord.py` works - this features will require a huge amount of jerry-rigging or a complete rewrite, and I am NOT ready to do this.

### CODE REVIEW

**Review by fourjr — CHANGES_REQUESTED** [review]
PR is invalid. No relevant changes.

**Comment by User-green** [comment]
> PR is invalid. No relevant changes.

This fixes problem in version check when running on 3.10.x. If you do not need it, I will gladly remove this request.

**Comment by voidstarone** [comment]
@fourjr  You are mistaken. The version check is broken when starting this.
```
You are using an unsupported version of Python.
Please upgrade to at least Python 3.5 to use discord-cli
You are currently on 3.10.1
```

**Comment by User-green** [comment]
"No valid changes"

**Pull request closed without merging**
